server:
  port: 8181

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/springboothibernate"
    username: "springboothibernate"
    password: "springboothibernate"

# Metrics related configurations
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web.exposure.include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

